### ISSUE TITLE
태그정보 가져오기 실패: NoSuchMethodError: The method '[]' was called on null.

### ISSUE THREAD

**Issue by Hansmic** [baeharam/Privacy-of-Animal#10]
태그정보 가져오기 실패: NoSuchMethodError: The method '[]' was called on null.
[        ] I/flutter ( 4673): Receiver: null
[        ] I/flutter ( 4673): Tried calling: [](0)
[+19133 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.handong.privacyofanimal/cache/Privacy-of-Animal-masterIPBFVV/Privacy-of-Animal-master/)
[   +2 ms] Sending to VM service: _deleteDevFS({fsName: Privacy-of-Animal-master})
[  +49 ms] Result: {type: Success}
[        ] DevFS: Deleted filesystem on the device (file:///data/user/0/com.handong.privacyofanimal/cache/Privacy-of-Animal-masterIPBFVV/Privacy-of-Animal-master/)
[   +4 ms] Sending to VM service: ext.flutter.exit({isolateId: isolates/493198602})
[   +5 ms] Result: {type: Sentinel, kind: Collected, valueAsString: <collected>}

**Comment by Hansmic** [comment]
it was initiating good doe, until today

**Comment by baeharam** [comment]
@Hansmic  It is under development and I cannot know what you mean.
